# Generated by Django 4.0.6 on 2022-07-25 08:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=70, verbose_name='تیتر اطلاعیه')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/notifications', verbose_name='عکس اطلاعیه')),
                ('text', ckeditor.fields.RichTextField(db_index=True, verbose_name='متن اطلاعیه')),
                ('create_date', models.CharField(editable=False, max_length=20, verbose_name='تاریخ ایجاد شده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'اطلاعیه',
                'verbose_name_plural': 'اطلاعیه ها',
            },
        ),
    ]
