# Generated by Django 4.0.6 on 2022-07-25 08:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'notification', 'verbose_name_plural': 'notifications'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='متن اطلاعیه'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=70, verbose_name='تیتر اطلاعیه'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['title', 'text', 'image'], name='notificatio_title_101311_idx'),
        ),
    ]
