# Generated by Django 4.0.6 on 2022-08-27 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forexdata',
            options={'verbose_name': 'Forex', 'verbose_name_plural': 'Forex'},
        ),
    ]
