# Generated by Django 4.0.6 on 2022-08-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0004_alter_forexdata_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forexdata',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='price'),
        ),
    ]
