# Generated by Django 4.0.6 on 2022-08-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_news', models.CharField(max_length=100, verbose_name='تیتر خبر')),
                ('img_news', models.CharField(blank=True, max_length=300, null=True, verbose_name='آدرس عکس خبر')),
                ('url_news', models.CharField(max_length=500, verbose_name='آدرس خبر')),
                ('datatime', models.CharField(max_length=50, verbose_name='ساعت انتشار')),
                ('text', models.CharField(max_length=500, verbose_name='متن کوتاه خبر')),
            ],
            options={
                'verbose_name': 'crypto',
                'verbose_name_plural': 'crypto',
                'ordering': ('id',),
            },
        ),
        migrations.AddIndex(
            model_name='datanews',
            index=models.Index(fields=['title_news', 'img_news', 'text'], name='crypto_data_title_n_78fd91_idx'),
        ),
    ]
