# Generated by Django 4.0.6 on 2022-08-22 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_alter_datanews_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datanews',
            old_name='datatime',
            new_name='datetime',
        ),
    ]
