# Generated by Django 4.0.6 on 2022-08-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_rename_datatime_datanews_datetime'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataNews',
            new_name='CrptDataNews',
        ),
        migrations.RemoveIndex(
            model_name='crptdatanews',
            name='crypto_data_title_n_78fd91_idx',
        ),
        migrations.AddIndex(
            model_name='crptdatanews',
            index=models.Index(fields=['title_news', 'img_news', 'text'], name='crypto_crpt_title_n_d93d39_idx'),
        ),
    ]
