# Generated by Django 4.0.6 on 2022-07-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_news', models.CharField(choices=[('carousel1', 'SLIDER'), ('box173', 'LEFT_SIDE_NEWS'), ('box172', 'BOTTOM_NEWS'), ('box157', 'LAST_NEWS')], max_length=30, verbose_name='مکان بارگزاری خبر')),
                ('title_news', models.CharField(max_length=100, verbose_name='تیتر خبر')),
                ('img_news', models.ImageField(blank=True, null=True, upload_to='images/news', verbose_name='عکس خبر')),
                ('url_news', models.CharField(max_length=500, verbose_name='آدرس خبر')),
            ],
            options={
                'verbose_name': 'اطلاعات خبر بورس',
                'verbose_name_plural': 'اطلاعات اخبار بورس',
            },
        ),
        migrations.AddIndex(
            model_name='datanews',
            index=models.Index(fields=['place_news', 'title_news', 'img_news'], name='bourse_data_place_n_e4368f_idx'),
        ),
    ]
