# Generated by Django 4.0.6 on 2022-07-25 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bourse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datanews',
            options={'verbose_name': 'bourse', 'verbose_name_plural': 'bourse'},
        ),
    ]
