# Generated by Django 4.0.6 on 2022-08-22 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bourse', '0003_alter_datanews_img_news_alter_datanews_place_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datanews',
            options={'ordering': ('id',), 'verbose_name': 'bourse', 'verbose_name_plural': 'bourse'},
        ),
    ]
