# Generated by Django 4.0.6 on 2022-08-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourse', '0004_alter_datanews_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataNews',
            new_name='BrsDataNews',
        ),
        migrations.RemoveIndex(
            model_name='brsdatanews',
            name='bourse_data_place_n_e4368f_idx',
        ),
        migrations.AddIndex(
            model_name='brsdatanews',
            index=models.Index(fields=['place_news', 'title_news', 'img_news'], name='bourse_brsd_place_n_0b7a5a_idx'),
        ),
    ]
